import { TextComponentProps } from '../../../theme/themeConfig'
export const darkTheme: TextComponentProps = {
    color: 'blue',
    text: '默认dark',
    fontSize: '12px',
    fontFamily: '',
    fontWeight: '',
    fontStyle: '',
    textDecoration: '',
    lineHeight: '',
    textAlign: '',
    backgroundColor: 'black',
    actionType: '',
    url: '',
    height: '',
    width: '',
    paddingLeft: '',
    paddingRight: '',
    paddingTop: '',
    paddingBottom: '',
    borderStyle: '',
    borderColor: '',
    borderWidth: '',
    borderRadius: '',
    boxShadow: '',
    opacity: '',
    position: '',
    left: '',
    top: '',
    right: ''
}