language: node_js
node_js:
- 14.18.1
branches:                   
  only:
  - feature/ss-ui-from-master
before_install:
 - npm i -g yarn
cache:
  npm: false
install:
  - npm i -g rollup
  - npm i -g cross-env
  - yarn
  - yarn build-prod
deploy:
  provider: npm
  email: 10430756409@qq.com
  skip_cleanup: true
  api_key:
    secure: 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
  on:
    all_branches: true

