language: node_js
node_js:
- 14.18.1
before_install:
 - npm i -g yarn
cache:
  npm: false
install:
  - npm i -g rollup
  - npm i -g cross-env
  - yarn
  - yarn build-prod
deploy:
  provider: npm
  email: 10430756409@qq.com
  skip_cleanup: true
  api_key:
    secure: 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
  on:
    tags: true

